### ISSUE TITLE
Binaries shouldn't be commited to Git

### ISSUE THREAD

**Issue by Calinou** [manipuladordedados/SuperCoder#1]
[You seem to commit binaries to the Git repository.](https://github.com/manipuladordedados/SuperCoder/tree/master/bin) You probably shouldn't, because:
- They clog up history.
- They make cloning slower, since you have more to download.
- Building from source is easy.

**Comment by lobovit** [comment]
@Calinou Ok, but, where there's binary in this script?

**Comment by manipuladordedados** [comment]
The folder name is "bin", ok. But the files in this folder are just Python scripts without the extension.

**Comment by Calinou** [comment]
Okay then.
